const titles = {
    "animegirl(1).png": "Elegant Anime Girl with Floral Background",
    "animegirl(2).png": "Aesthetic Anime Girl in School Uniform",
    "animegirl(3).png": "Sad Anime Girl Looking at the Sky",
    "animegirl(4).png": "Stylish Anime Girl with Modern Vibes",
    "animegirl(5).png": "Beautiful Anime Girl Surrounded by Butterflies",
    "animegirl(6).png": "Anime Girl Standing Under a Starry Night",
    "animegirl(7).png": "Minimalist Anime Girl with Calm Expression",
    "animegirl(8).png": "Aesthetic Anime Girl with Teary Eyes",
    "animegirl(9).png": "Anime Girl in Traditional Japanese Dress",
    "animegirl(10).png": "Anime Girl with Rainbow-Colored Hair",
    "animegirl(11).png": "Sad Anime Girl with an Umbrella in the Rain",
    "animegirl(12).png": "Anime Girl Wearing a Floral Shirt",
    "animegirl(13).png": "Feminine Look Anime Girl Aesthetic",
    "animegirl(14).png": "Aesthetic Anime Girl with Flowing Hair",
    "animegirl(15).png": "Anime Girl with Artistic Butterfly Pattern",
    "animegirl(16).png": "Aesthetic Anime Girl Staring into Space",
    "animegirl(17).png": "Anime Girl in a Collage Art Style",
    "animegirl(18).png": "Half-Demon Anime Girl with Splash Art",
    "animegirl(19).png": "Pink Aesthetic Anime Girl Striking a Pose",
    "animegirl(20).png": "Anime Girl Holding a Comet in a Starry Sky",
    "animegirl(21).png": "Aesthetic Anime Girl with Black and White Vibes",
    "animegirl(22).png": "Minimalist Anime Girl with Abstract Background",
    "animegirl(23).png": "Anime Girl with Dreamy Chinese Dress",
    "animegirl(24).png": "Aesthetic Anime Girl with a Peaceful Smile",
    "animegirl(25).png": "Blonde Anime Girl with Artistic Charm",
    "animegirl(26).png": "Anime Goddess Beauty Illustration",
    "animegirl(27).png": "Anime Girl with a Digital Art Comet",
    "animegirl(28).png": "Kawaii Anime Girl in Stylish Attire",
    "animegirl(29).png": "Anime Girl with a Cute Dynamic Pose",
    "animegirl(30).png": "Anime Girl in Minimalist Monochrome",
    "animegirl(31).png": "Collage Art Style Anime Girl",
    "animegirl(32).png": "Anime Girl with a Face Mask",
    "animegirl(33).png": "Black and White Sad Anime Girl",
    "animegirl(34).png": "Anime Girl with Delicate Aesthetic Details",
    "animegirl(35).png": "Beautiful Aesthetic Anime Girl with Leaves",
    "animegirl(36).png": "Anime Girl with Pastel Colors and Flowers",
    "animegirl(37).png": "Dreamy Anime Girl in Vibrant Colors",
    "animegirl(38).png": "Stylish Anime Girl with a Phone",
    "animegirl(39).png": "Anime Girl in a Minimalist Fantasy Scene",
    "animegirl(40).png": "Anime Girl with an Abstract Floral Background",
    "animegirl(41).png": "Sad Anime Girl with a Digital Art Style",
    "animegirl(42).png": "Aesthetic Anime Girl with a Beautiful Pose",
    "animegirl(43).png": "Anime Girl in an Elegant and Calm Mood",
    "animegirl(44).png": "Cute Anime Girl with Vibrant Hair",
    "animegirl(45).png": "Dreamy Anime Girl with Butterfly Details",
    "animegirl(46).png": "Aesthetic Anime Girl Facing the Horizon",
};

export default titles;
