const titles = {
  "Goku(1).jpeg": "Goku #bro #wallpaper",
  "Goku(2).jpeg": "Vegeta",
  "Goku(3).jpeg": "Frieza",
  "Goku(4).jpeg": "640 Best Dragon Ball Wallpapers Ideas | Dragon Ball Wallpapers, Dragon Ball, Anime Dragon Ball",
  "Goku(5).jpeg": "Dragon Ball Z HD Wallpapers. #Awesome Wallpapers. #Goku Wallpapers. #Swager. #Iphone 11Pro",
  "Goku(6).jpeg": "Goku - Dragon Ball Wallpaper 🐲‼️",
  "Goku(7).jpeg": "Most Popular Dragon Ball Goku Wallpapers",
  "Goku(8).jpeg": "Dragon Ball Z Wallpapers for iPhone",
  "Goku(9).jpeg": "Dragon Ball Z iPhone Backgrounds",
  "Goku(10).jpeg": "100+] Goku and Vegeta iPhone Wallpapers | Wallpapers.com",
  "Goku(11).jpeg": "Dragonball Super",
  "Goku(12).jpeg": "Dragon Ball Z iPhone Wallpaper",
  "Goku(13).jpeg": "Goku Wallpaper 4K, Dragon Ball, AMOLED, Retro",
  "Goku(14).jpeg": "Goku Wallpaper iPhone",
  "Goku(15).jpeg": "Goku Blue Sky Wallpapers - Dragon Ball Z Wallpapers iPhone",
  "Goku(16).jpeg": "Goku iPhone Wallpaper - iPhone Anime Wallpapers",
  "Goku(17).jpeg": "Dragon Ball Z Ultra HD Wallpapers",
  "Goku(18).jpeg": "Powerful Dragon Ball Goku Wallpapers",
  "Goku(19).jpeg": "Goku Fighting Wallpapers - Dragon Ball Z",
  "Goku(20).jpeg": "Epic Dragon Ball Goku Wallpapers for Your Phone",
  "Goku(21).jpeg": "Dragon Ball Z iPhone Wallpapers for Fans",
  "Goku(22).jpeg": "Goku in Action - Dragon Ball Z Wallpapers",
  "Goku(23).jpeg": "Dragon Ball Z Epic Wallpapers for iPhone",
  "Goku(24).jpeg": "Goku Ultra Instinct Wallpapers",
  "Goku(25).jpeg": "Super Saiyan Goku Wallpapers for iPhone",
  "Goku(26).jpeg": "Dragon Ball Z Backgrounds for iPhone",
  "Goku(27).jpeg": "HD Goku Wallpapers - Dragon Ball Z",
  "Goku(28).jpeg": "Vegeta and Goku Wallpapers",
  "Goku(29).jpeg": "Dragon Ball Super Wallpapers for iPhone",
  "Goku(30).jpeg": "Dragon Ball Z iPhone Lockscreen Wallpapers",
  "Goku(31).jpeg": "Goku SSJ Wallpapers for iPhone",
  "Goku(32).jpeg": "Dragon Ball Z Icons and Wallpapers",
  "Goku(33).jpeg": "Dragon Ball Super HD Wallpapers",
  "Goku(34).jpeg": "Dragon Ball Z 4K Wallpapers - Goku and Friends",
  "Goku(35).jpeg": "Dragon Ball Goku iPhone Wallpapers",
  "Goku(36).jpeg": "Super Saiyan Goku Wallpapers for iPhone 12",
  "Goku(37).jpeg": "Goku and Vegeta Wallpapers for iPhone",
  "Goku(38).jpeg": "Dragon Ball Z SSJ Wallpapers",
  "Goku(39).jpeg": "Epic Dragon Ball iPhone Wallpapers",
  "Goku(40).jpeg": "Dragon Ball Super iPhone Wallpapers",
  "Goku(41).jpeg": "4K Dragon Ball Z Goku Wallpapers",
  "Goku(42).jpeg": "Dragon Ball Z Wallpapers for Android",
  "Goku(43).jpeg": "Goku SSJ3 Wallpapers",
  "Goku(44).jpeg": "Dragon Ball Z iPhone 11 Wallpapers",
  "Goku(45).jpeg": "Ultra Instinct Goku Wallpapers",
  "Goku(46).jpeg": "Dragon Ball Z 4K Ultra Wallpapers",
  "Goku(47).jpeg": "Goku iPhone X Wallpapers",
  "Goku(48).jpeg": "Super Saiyan Blue Goku Wallpapers",
  "Goku(49).jpeg": "Dragon Ball Z Wallpapers for Your Device",
  "Goku(50).jpeg": "Goku 4K Wallpaper - Dragon Ball Z",
  "Goku(51).jpeg": "Goku and Vegeta Super Saiyan Wallpapers",
  "Goku(52).jpeg": "Dragon Ball Z Wallpapers for the Ultimate Fan",
  "Goku(53).jpeg": "Dragon Ball Z 1080p Wallpapers",
  "Goku(54).jpeg": "Dragon Ball Z Goku Super Saiyan God Wallpapers",
  "Goku(55).jpeg": "Goku Fist Bump Wallpapers - Dragon Ball Z",
  "Goku(56).jpeg": "Vegeta Wallpapers for iPhone",
  "Goku(57).jpeg": "Goku and Friends Wallpapers",
  "Goku(58).jpeg": "Dragon Ball Z: The Saiyan Saga Wallpapers",
  "Goku(59).jpeg": "Dragon Ball Z iPhone XS Wallpapers",
  "Goku(60).jpeg": "Goku Power Up Wallpapers - Dragon Ball Z"
};

export default titles;
